// Mocks generated by Mockito 5.4.4 from annotations
// in frontend/test/feedback_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:frontend/context/auth_provider.dart' as _i8;
import 'package:frontend/context/dashboard_provider.dart' as _i6;
import 'package:frontend/context/feedback_provider.dart' as _i3;
import 'package:frontend/core/models/dashboard_model.dart' as _i2;
import 'package:frontend/core/models/session_model.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDashboardSummary_0 extends _i1.SmartFake
    implements _i2.DashboardSummary {
  _FakeDashboardSummary_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRadarData_1 extends _i1.SmartFake implements _i2.RadarData {
  _FakeRadarData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FeedbackProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedbackProvider extends _i1.Mock implements _i3.FeedbackProvider {
  MockFeedbackProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> fetchReport(
    String? sessionId, {
    int? retries = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchReport,
          [sessionId],
          {#retries: retries},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DashboardProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardProvider extends _i1.Mock implements _i6.DashboardProvider {
  MockDashboardProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DashboardSummary get summary => (super.noSuchMethod(
        Invocation.getter(#summary),
        returnValue: _FakeDashboardSummary_0(
          this,
          Invocation.getter(#summary),
        ),
      ) as _i2.DashboardSummary);

  @override
  _i2.RadarData get radarData => (super.noSuchMethod(
        Invocation.getter(#radarData),
        returnValue: _FakeRadarData_1(
          this,
          Invocation.getter(#radarData),
        ),
      ) as _i2.RadarData);

  @override
  List<_i7.SessionModel> get history => (super.noSuchMethod(
        Invocation.getter(#history),
        returnValue: <_i7.SessionModel>[],
      ) as List<_i7.SessionModel>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> fetchDashboardData() => (super.noSuchMethod(
        Invocation.method(
          #fetchDashboardData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> fetchHistory({String? moduleType}) => (super.noSuchMethod(
        Invocation.method(
          #fetchHistory,
          [],
          {#moduleType: moduleType},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i8.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitializing => (super.noSuchMethod(
        Invocation.getter(#isInitializing),
        returnValue: false,
      ) as bool);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  String get profession => (super.noSuchMethod(
        Invocation.getter(#profession),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#profession),
        ),
      ) as String);

  @override
  List<String> get skills => (super.noSuchMethod(
        Invocation.getter(#skills),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String get voiceId => (super.noSuchMethod(
        Invocation.getter(#voiceId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#voiceId),
        ),
      ) as String);

  @override
  String get profileImageUrl => (super.noSuchMethod(
        Invocation.getter(#profileImageUrl),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#profileImageUrl),
        ),
      ) as String);

  @override
  String get displayName => (super.noSuchMethod(
        Invocation.getter(#displayName),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#displayName),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setBypassAuthenticated() => super.noSuchMethod(
        Invocation.method(
          #setBypassAuthenticated,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> register(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            displayName,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> fetchProfileData() => (super.noSuchMethod(
        Invocation.method(
          #fetchProfileData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserProfile({
    String? name,
    String? imageUrl,
    String? profession,
    List<String>? skills,
    String? voiceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #name: name,
            #imageUrl: imageUrl,
            #profession: profession,
            #skills: skills,
            #voiceId: voiceId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateFcmToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #updateFcmToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
