const { getSessionById, updateSessionState, INTERVIEW_STATES } = require('../../models/session');
const { saveTranscript } = require('../../models/transcript');

const SILENCE_THRESHOLD = 5; // BE-BUG #5 FIX: was 3, too aggressive for interviews
const MAX_TURNS = 20;

// BUG FIX: this used naive substring matching, so a candidate saying "we store
// it as a byte array" ('bye'), "I stopped using Redis" / "it runs nonstop"
// ('stop') or "that's all the traffic we handled" had their interview
// terminated mid-answer. Matching is now anchored on word boundaries, the
// ambiguous single words are gone, and the remaining phrases must be a
// standalone statement rather than a clause buried in a technical answer.
// Short, ambiguous phrases must close out the utterance — "That's all." ends an
// interview, "that's all the traffic we handled that quarter" does not.
const TERMINAL_EXIT_PATTERNS = [
  /\bi(?:'m| am) done\b\W*$/,
  /\bthat(?:'s| is) all\b\W*$/,
  /\bno more questions\b\W*$/,
  /\bgood ?bye\b\W*$/
];

// Explicit, unambiguous requests — safe to match anywhere in the utterance.
const EXPLICIT_EXIT_PATTERNS = [
  /\bend (?:the |this )?interview\b/,
  /\bstop (?:the |this )?interview\b/,
  /\bend (?:the |this )?session\b/,
  /\bfinish (?:the |this )?interview\b/
];

// Secondary guard: a genuine exit is short and deliberate, never a paragraph.
const MAX_EXIT_INTENT_WORDS = 15;

function detectExitIntent(text) {
  if (!text) return false;
  const normalized = text.toLowerCase().trim();
  if (normalized.split(/\s+/).length > MAX_EXIT_INTENT_WORDS) return false;
  return EXPLICIT_EXIT_PATTERNS.some(p => p.test(normalized))
    || TERMINAL_EXIT_PATTERNS.some(p => p.test(normalized));
}

exports.handler = async (event) => {
  try {
    const body = JSON.parse(event.body || '{}');
    const { sessionId, textTranscript, isSilence, currentConceptId } = body;

    if (!sessionId) {
      return { statusCode: 400, body: JSON.stringify({ error: 'sessionId required' }) };
    }

    const userId = event.requestContext?.authorizer?.uid;
    const session = await getSessionById(sessionId);
    if (!session) {
      return { statusCode: 404, body: JSON.stringify({ error: 'Session not found' }) };
    }

    if (session.userId !== userId) {
      return { statusCode: 403, body: JSON.stringify({ error: 'Forbidden' }) };
    }

    const turnIndex = session.turnCount || 0;

    // Handle silence
    if (isSilence) {
      const silenceRetries = (session.silenceRetries || 0) + 1;
      
      if (silenceRetries >= SILENCE_THRESHOLD) {
        return {
          statusCode: 200,
          body: JSON.stringify({
            shouldTerminate: true,
            reason: 'SILENCE_TIMEOUT'
          })
        };
      }

      // BE-BUG #18 FIX: transition to SILENCE_DETECTED state, not stay in current state
      await updateSessionState(sessionId, INTERVIEW_STATES.SILENCE_DETECTED, null, { silenceRetries });

      return {
        statusCode: 200,
        body: JSON.stringify({
          shouldTerminate: false,
          nextAIResponse: "I didn't catch that. Could you please repeat?",
          silenceRetries
        })
      };
    }

    // Save user transcript
    await saveTranscript(sessionId, turnIndex, 'USER', textTranscript);

    // Check exit intent
    if (detectExitIntent(textTranscript)) {
      return {
        statusCode: 200,
        body: JSON.stringify({
          shouldTerminate: true,
          reason: 'USER_EXIT'
        })
      };
    }

    // Check max turns
    if (turnIndex >= MAX_TURNS) {
      return {
        statusCode: 200,
        body: JSON.stringify({
          shouldTerminate: true,
          reason: 'MAX_TURNS_REACHED'
        })
      };
    }

    // Preserve the current session state while persisting concept selection and reset silence retries.
    // PERF-FIX #5: return the ALL_NEW attributes so the async worker does not
    // need a second GetItem to see the updated session.
    const updatedSession = await updateSessionState(sessionId, session.currentState, null, {
      currentConceptId: currentConceptId || session.currentConceptId,
      silenceRetries: 0
    });

    return {
      statusCode: 200,
      body: JSON.stringify({
        shouldTerminate: false,
        nextAIResponse: null, // Will be generated by generateAtomicTurn
        session: updatedSession || null
      })
    };

  } catch (error) {
    console.error('Process User Input Error:', error);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: error.message })
    };
  }
};
